#login
USERNAME_INPUT="//input[@id='id_username']"
PASSWORD_INPUT="//input[@id='id_password']"
LOGIN_BUTTON="//button[text()='Đăng nhập']"
#thaotacnhanh
BTN_coursemanagement="//a[contains(@class,'btn-success') and @href='/en/academics/courses/']"
Menu_HP="//a[@href='/en/academics/courses/']"
BTN_TEST="//a[contains(@class,'btn-warning') and @href='/en/assessment/tests/']"
Menu_BKT="//a[@href='/en/assessment/tests/' and contains(@class,'menu-item')]"
BTN_HOME="//nav[@aria-label='breadcrumb']//a[@href='/en/' and normalize-space()='Trang chủ']"
BTN_Ques="//a[contains(@class,'btn-info') and @href='/en/questionbank/questions/']"
Menu_Ques="//a[@href='/en/questionbank/questions/' and contains(@class,'menu-item')]"
Menu_HOME="//a[@href='/en/' and contains(@class,'menu-item')]"
#chuontrinhdaotao
Menu_ProGram="//a[@href='/en/academics/programs/']"
BTN_PRO="//li[contains(@class,'breadcrumb-item')]/a[contains(text(),'Quản lý chương trình')]" 
BTN_VIEW_PROGRAM="//a[contains(@class,'btn-info') and @href='/en/academics/programs/20/']"
BTN_VIEW_COURSE="//a[contains(@class,'btn-success') and @href='/en/academics/programs/20/courses/']"
BTN_SEARCH="//button[i[contains(@class,'fa-search')]]"
TXT_SEARCH="//input[@name='q']"
CLICK_NEXT="//a[@class='page-link' and text()='2']"
CLICK_PREVIOUS="//li[@class='page-item']/a[@aria-label='Previous']"
BTN_COPPY_PROGRAM="//button[@data-bs-target='#duplicateProgramModal']"
BTN_SUBMIT="//button[contains(.,'Xác nhận sao chép') and .//i[contains(@class,'fa-copy')]]"
BTN_CREATE_STUDYSECTION="//a[@href='/en/academics/programs/20/courses/create/']"
INPUT_COURSE_CODE="//input[@id='id_course_code']"
INPUT_COURSE_NAME="//input[@id='id_course_name']"
INPUT_COURSE_CREDIT="//input[@name='credits']"
INPUT_COURSE_DESCRIPTION="//textarea[@name='description']"
SELECT_TYPE="(//select[@name='type'])[1]"
SELECT_STATUS="//select[@id='id_status']"
SELECT_Prerequisitecourses="//select[@id='id_prerequisite_courses']/option[@value='4']"
SELECT_PROGRAM="//select[@id='id_program']/option[@value='4']"
BTN_CREATE_COURSE="//button[@type='submit' and contains(.,'Create Course')]"
BTN_BACK_PROGRAM="//a[@href='/en/academics/programs/20/']"
#hocphan
BTN_EDIT_COURSE="//a[@href='/en/academics/courses/126/update/']"
ITEM_COURSE="//a[contains(.,'Học phần')]"
ICON_VIEW="//a[@href='/en/academics/courses/126/']"
BTN_SEARCH_COURSE="//button[contains(@class,'btn-primary')]"
INPUT_SEARCH="//input[contains(@class,'form-control') and @name='q']"
# INPUT_CODE="//input[@id='id_course_code']"
# INPUT_NAME="//input[@id='id_course_name']"
BTN_UPDATE="//button[@type='submit' and contains(.,'Update Course')]"      
BTN_BACK_COURSE="//li[@class='breadcrumb-item']/a[@href='/en/academics/courses/']"
BTN_PROGRAM="//a[contains(@class,'btn-secondary') and contains(.,'Programs')]"
#clo
VIEW_CLO="//a[@href='/en/academics/courses/126/clos/']"
BTN_CREATE_CLO="//a[@href='/en/academics/courses/126/clos/create/']"
CREATE_CLO="//button[@type='submit' and contains(.,'Create CLO')]"
INPUT_CLO_CODE="//input[@id='id_clo_code']"
CLO_DESCRIPTION="//textarea[@id='id_description']"
SELECT_CLO_CATEGORY="//select[@id='id_category']"
SELECT_CLO_LEVEL="//select[@id='id_level']"
INPUT_CLO_WEIGHT="//input[@id='id_weight']"
SELECT_ASSESSMENT_CLO="//select[@id='id_assessment_method']"
EDIT_CLO="//a[@href='/en/academics/clos/229/update/' and contains(@class,'btn-primary')]"
UPDATE_CLO="//button[@type='submit' and contains(.,'Update CLO')]"
#lophoc
ITEM_CLASS="//a[contains(.,'Lớp học')]"
SELECT_SEMESTER="//select[@id='semester']"
SELECT_ACADEMICYEAR="//select[@id='academic_year']"
SELECT_STATUS="//select[@id='status']"
INPUT_SEARCH_CLASS="//input[@name='q']"
BTN_SEARCH_CLASS="//button[i[contains(@class,'fa-search')]]"
BTN_CREATE_CLASS="//a[@href='/en/academics/courses/' and contains(.,'Create Class')]"

