LOGO = '//div[@class="logo"]'
USER = '//div[@class="user-avatar"]'
## DashBoard
MESSAGE_ERROR_LOGIN_V = '//div[@class="alert alert-error"]'
MESSAGE_ERROR_LOGIN_E = '//div[@class="alert alert-danger"]'

BOX_ADVERTISE = '//div[@id="djDebugToolbar"]'
LINK_HANDLE = '//a[@id="djHideToolBarButton"]'

LINK_QUICK_OPERATION = '//a[@href="/en/academics/programs/create/"]'
ACTUAL_QUICK_OPERATION = '//h1[text()="403 Forbidden"]'
##Chương trình đào tạo
URL_CTDT = '//a[@href="/en/academics/programs/"]'
TITLE_PAGE = '//h1[@class="content-title"]'

INPUT_SEARCH = '//input[@placeholder="Search programs..."]'
BTN_SEARCH = '//button[@class="btn btn-primary"]'

EXPECTED_SEARCH = '//table[contains(@class, "table-hover")]//tbody/tr/td[1]'
ACTUAL_SEARCH_NOT = '//div[@class="alert alert-info"]'

NAME_EXPECTED = '//table[contains(@class, "table-hover")]//tbody/tr[1]/td[1]'
DEPARTMENT_EXPECTED = '//table[contains(@class, "table-hover")]//tbody/tr[1]/td[2]'
TIME_EXPECTED = '//table[contains(@class, "table-hover")]//tbody/tr[1]/td[3]'
STATUS_EXPECTED = '//table[contains(@class, "table-hover")]//tbody/tr[1]/td[4]/span'
VERSION_EXPECTED = '//table[contains(@class, "table-hover")]//tbody/tr[1]/td[last()-1]'
URL_INFO = '//a[@href="/en/academics/programs/5/"]'

NAME_ACTUAL = '//h5[text()="Công nghệ thông tin"]'
DEPARTMENT_ACTUAL = '//p[@class="text-muted mb-2"]'
TIME_ACTUAL = '//p[text()="Jan. 1, 2024"]'
STATUS_ACTUAL = '//div[@class="card-body"]//div[1]//span[contains(text(),"Active")]'
VERSION_ACTUAL = '//p[text()="K2024"]'
DSHP_ACTUAL = '//h6[contains(text(),"Danh sách Học phần")]'

URL_PLO = '//a[@href="/en/academics/programs/5/plos/create/"]'
INPUT_PLO_CODE= '//input[@id="id_plo_code"]'
TEXTAREA_DESCRIPTION ='//textarea[@id="id_description"]'
SELECT_CATEGORY ='//select[@id="id_category"]'
SELECT_LEVEL ='//select[@id="id_level"]'
INPUT_VERSION = '//input[@id="id_version"]'
BTN_CREATE = '//button[@class="btn btn-primary"]'
ACTUAL_PLO = "(//div[@id='ploAccordion']//div[contains(@class, 'accordion-item')])[last()]//h2//strong"
URL_EXIT_PLO = '//a[@href="/en/academics/programs/5/" and @class = "btn btn-secondary"]'

URL_CREATE_SECTION_STUDY ='//a[@href="/en/academics/programs/5/courses/create/"]'
INPUT_COURSE_CODE = '//input[@id="id_course_code"]'
INPUT_COURSE_NAME = '//input[@id="id_course_name"]'
INPUT_CREDITS = '//input[@id="id_credits"]'
TEXTAREA_DESCRIPTION_COURSE = '//textarea[@id="id_description"]'
SELECT_TYPE_COURSE = '//select[@id="id_type"]'
CHECKBOX_CORE_SUBJECT = '//input[@id="id_is_core"]'
SELECT_STATUS_COURSE = '//select[@id="id_status"]'
BTN_CREATE_COURSE = '//button[@class="btn btn-primary"]'

ACTUAL_COURSE_CODE = '//table[@class="table table-bordered"]//tbody/tr[last()]/td[1]/strong'
ACTUAL_COURSE_NAME = '//table[@class="table table-bordered"]//tbody/tr[last()]/td[2]'
ACTUAL_COURSE_CREDITS = '//table[@class="table table-bordered"]//tbody/tr[last()]/td[3]'
ACTUAL_COURSE_TYPE = '//table[@class="table table-bordered"]//tbody/tr[last()]/td[4]/span'
ACTUAL_COURSE_STATUS = '//table[@class="table table-bordered"]//tbody/tr[last()]/td[last()-1]/span'

MESSAGE_ACTUAL_COURSE = '//div[@class="alert alert-success alert-dismissible fade show"]'

URL_ALL_SECTION_STUDY = '//a[@href="/en/academics/programs/5/courses/"]'
ACTUAL_ALL_SECTION_STUDY = '//h1[contains(text(),"Courses for Công nghệ thông tin")]'
URL_COURSE_DETAILS = '//a[@href="/en/academics/courses/45/"]'
ACTUAL_COURSE_DETAILS ='//h6[contains(text(),"Thông tin học phần")]'

URL_EDIT_COURSE = '//a[@href="/en/academics/courses/45/update/"]'
ACTUAL_EDIT_COURSE = '//h1[@class="content-title"]'
URL_BACK_TO_COURSE = '//a[@class="btn btn-secondary"]'

URL_CREATE_CLASS = '//a[@href="/en/academics/courses/45/classes/create/" and @class="btn btn-info"]'
ACTUAL_CREAT_CLASS = '//h1[@class="content-title"]'
INPUT_SEMESTER = '//input[@id="id_semester"]'
INPUT_ACADEMIC_YEAR = '//input[@id="id_academic_year"]'
SELECT_STATUS_CLASS = '//select[@id="id_status"]'
INPUT_START_DATE = '//input[@id="id_start_date"]'
INPUT_END_DATE = '//input[@id="id_end_date"]'
INPUT_ROOM= '//input[@id="id_room"]'
INPUT_MAX_STUDENTS = '//input[@id="id_max_students"]'
TEXTATEA_SCHEDULE = '//textarea[@id="id_schedule"]'
CREAT_CLASS_BTN = '//button[@class="btn btn-primary"]'

URL_BACK_TO_COURSE_DETAILS = '//a[@href="/en/academics/programs/5/courses/"]'
ACTUAL_BACK_TO_COURSE_DETAILS = '//h1[contains(text(),"Courses for Công nghệ thông tin")]'

URL_PAGE_CLOS = '//a[@href="/en/academics/courses/45/clos/"]'
ACTUAL_TITLE_CLOS = '//h1[contains(text(),"CLOs for CNTT011 - Kiểm thử phần mềm12")]'
URL_ADD_CLO = '//a[@href="/en/academics/courses/45/clos/create/"]'
INPUT_CLO_CODE = '//input[@id="id_clo_code"]'
TEXTAREA_DESCRIPTION_CLO = '//textarea[@id="id_description"]'
SELECT_CATEGORY_CLO = '//select[@id="id_category"]'
SELECT_LEVEL_CLO = '//select[@id="id_level"]'
INPUT_WEIGHT_CLO = '//input[@id="id_weight"]'
SELECT_ASSESSMENT_METHOD = '//select[@id="id_assessment_method"]'
CREATE_CLO_BTN = '//button[@class="btn btn-primary"]'
ACTUAL_MESSAGE_CLO= '//div[@class="alert alert-success alert-dismissible fade show"]'

ACTUAL_CLO_CODE = '//table[@class="table table-bordered table-hover"]/tbody/tr[1]/td[1]'
ACTUAL_DESCRIPTION_CLO = '//table[@class="table table-bordered table-hover"]/tbody/tr[1]/td[2]'
ACTUAL_CATEGORY_CLO = '//table[@class="table table-bordered table-hover"]/tbody/tr[1]/td[3]/span'
ACTUAL_LEVEL_CLO = '//table[@class="table table-bordered table-hover"]/tbody/tr[1]/td[4]/span'
ACTUAL_WEIGHT_CLO = '//table[@class="table table-bordered table-hover"]/tbody/tr[1]/td[5]'

ACTUAL_MESSAGE_CLO_ERROR= '//p[@id="error_1_id_clo_code"]'
URL_BACK_TO_CLOS = '//a[@href="/en/academics/courses/45/clos/"]'
URL_DETAILS_CLOS= '//a[@href="/en/academics/clos/122/"]'
TITLE_PAGE_DETAIL_CLOS = '//h6[contains(text(),"CLO Details")]'
URL_EDIT_CLOS='//a[@href="/en/academics/clos/122/update/"]'
TITLE_PAGE_EDIT_CLOS= '//h1[contains(text(),"Edit CLO")]'